<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\Ecommerce.Catalog.Contracts\Ecommerce.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\..\Users\Ecommerce.Modules.Users.Contracts\Ecommerce.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\Ecommerce.Order.Modules.Domain\Ecommerce.Order.Modules.Domain.csproj" />
  </ItemGroup>

</Project>
