<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ValueObjects\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Bson" Version="3.9.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Ecommerce.Domain\Ecommerce.Domain.csproj" />
  </ItemGroup>

</Project>
