<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Localization\Ecommerce.Localization.Abstractions\Ecommerce.Localization.Abstractions.csproj" />
    <ProjectReference Include="..\Ecommerce.Localization.Modules.Domain\Ecommerce.Localization.Modules.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Translation\GetById\" />
  </ItemGroup>

</Project>
