global using Ecommerce.Inventory.Modules.Infrastructure;
global using Ecommerce.Presentation;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
 global using Ecommerce.Inventory.Modules.Application.Features.ReserveStock;
global using MediatR;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;