<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentEmail.Razor" Version="3.0.2" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Ecommerce.Presentation\Ecommerce.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\Notifications\" />
  </ItemGroup>

</Project>
