<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0d5a475b-de8f-4e74-a374-70a597493294</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Admin\Ecommerce.Admin\Ecommerce.Admin.csproj" />
    <ProjectReference Include="..\..\Api\Ecommerce.API\Ecommerce.API.csproj" />
  </ItemGroup>

</Project>
