<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Ecommerce.Presentation\Ecommerce.Presentation.csproj" />
    <ProjectReference Include="..\Ecommerce.Basket.Modules.Infrastructure\Ecommerce.Basket.Modules.Infrastructure.csproj" />
  </ItemGroup>

</Project>
