<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Mongo\Ecommerce.Mongo\Ecommerce.Mongo.csproj" />
    <ProjectReference Include="..\Ecommerce.Basket.Modules.Application\Ecommerce.Basket.Modules.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Serializers\" />
  </ItemGroup>

</Project>
